// Mock list of popular flight numbers for demo purposes
export const MOCK_FLIGHTS = [
    { code: "AA1", label: "American Airlines: JFK -> LAX" },
    { code: "AA2", label: "American Airlines: LAX -> JFK" },
    { code: "AA3", label: "American Airlines: JFK -> LAX" },
    { code: "AA4", label: "American Airlines: LAX -> JFK" },
    { code: "AA50", label: "American Airlines: DFW -> LHR" },
    { code: "AA70", label: "American Airlines: DFW -> FRA" },
    { code: "AA80", label: "American Airlines: DFW -> LHR" },
    { code: "AA100", label: "American Airlines: JFK -> LHR" },
    { code: "AC1", label: "Air Canada: YYZ -> HND" },
    { code: "AC2", label: "Air Canada: HND -> YYZ" },
    { code: "AC3", label: "Air Canada: YVR -> NRT" },
    { code: "AC4", label: "Air Canada: NRT -> YVR" },
    { code: "AC33", label: "Air Canada: YVR -> SYD" },
    { code: "AC34", label: "Air Canada: SYD -> YVR" },
    { code: "AF2", label: "Air France: JFK -> CDG" },
    { code: "AF6", label: "Air France: JFK -> CDG" },
    { code: "AF10", label: "Air France: JFK -> CDG" },
    { code: "AF22", label: "Air France: JFK -> CDG" },
    { code: "AF66", label: "Air France: LAX -> CDG" },
    { code: "AI101", label: "Air India: DEL -> JFK" },
    { code: "AI102", label: "Air India: JFK -> DEL" },
    { code: "AI127", label: "Air India: DEL -> ORD" },
    { code: "AM1", label: "Aeroméxico: MEX -> MAD" },
    { code: "AM2", label: "Aeroméxico: MAD -> MEX" },
    { code: "AM400", label: "Aeroméxico: MEX -> JFK" },
    { code: "AS1", label: "Alaska Airlines: SEA -> DCA" },
    { code: "AS2", label: "Alaska Airlines: DCA -> SEA" },
    { code: "AS3", label: "Alaska Airlines: SEA -> DCA" },
    { code: "AS4", label: "Alaska Airlines: DCA -> SEA" },
    { code: "AY1", label: "Finnair: HEL -> LAX" },
    { code: "AY2", label: "Finnair: LAX -> HEL" },
    { code: "AY133", label: "Finnair: HEL -> SIN" },
    { code: "AZ608", label: "ITA Airways: FCO -> JFK" },
    { code: "AZ609", label: "ITA Airways: JFK -> FCO" },
    { code: "BA5", label: "British Airways: LHR -> HND" },
    { code: "BA6", label: "British Airways: HND -> LHR" },
    { code: "BA7", label: "British Airways: LHR -> HND" },
    { code: "BA11", label: "British Airways: LHR -> SIN" },
    { code: "BA12", label: "British Airways: SIN -> LHR" },
    { code: "BA55", label: "British Airways: LHR -> JNB" },
    { code: "BA117", label: "British Airways: LHR -> JFK" },
    { code: "BA175", label: "British Airways: LHR -> JFK" },
    { code: "BA206", label: "British Airways: MIA -> LHR" },
    { code: "BA269", label: "British Airways: LHR -> LAX" },
    { code: "BR10", label: "EVA Air: TPE -> YVR" },
    { code: "BR12", label: "EVA Air: TPE -> LAX" },
    { code: "BR32", label: "EVA Air: TPE -> JFK" },
    { code: "CA981", label: "Air China: PEK -> JFK" },
    { code: "CA982", label: "Air China: JFK -> PEK" },
    { code: "CI3", label: "China Airlines: TPE -> SFO" },
    { code: "CI4", label: "China Airlines: SFO -> TPE" },
    { code: "CI7", label: "China Airlines: TPE -> LAX" },
    { code: "CI8", label: "China Airlines: LAX -> TPE" },
    { code: "CX100", label: "Cathay Pacific: SYD -> HKG" },
    { code: "CX101", label: "Cathay Pacific: HKG -> SYD" },
    { code: "CX250", label: "Cathay Pacific: LHR -> HKG" },
    { code: "CX251", label: "Cathay Pacific: HKG -> LHR" },
    { code: "CX830", label: "Cathay Pacific: HKG -> JFK" },
    { code: "CX831", label: "Cathay Pacific: JFK -> HKG" },
    { code: "CX888", label: "Cathay Pacific: HKG -> YVR" },
    { code: "DL1", label: "Delta Air Lines: JFK -> LHR" },
    { code: "DL2", label: "Delta Air Lines: LHR -> JFK" },
    { code: "DL3", label: "Delta Air Lines: JFK -> LHR" },
    { code: "DL4", label: "Delta Air Lines: LAX -> JFK" },
    { code: "DL8", label: "Delta Air Lines: LAX -> HND" },
    { code: "DL20", label: "Delta Air Lines: SEA -> LHR" },
    { code: "DL106", label: "Delta Air Lines: JFK -> FRA" },
    { code: "EI104", label: "Aer Lingus: JFK -> DUB" },
    { code: "EI105", label: "Aer Lingus: DUB -> JFK" },
    { code: "EK1", label: "Emirates: DXB -> LHR" },
    { code: "EK2", label: "Emirates: LHR -> DXB" },
    { code: "EK3", label: "Emirates: DXB -> LHR" },
    { code: "EK4", label: "Emirates: LHR -> DXB" },
    { code: "EK73", label: "Emirates: DXB -> CDG" },
    { code: "EK201", label: "Emirates: DXB -> JFK" },
    { code: "EK202", label: "Emirates: JFK -> DXB" },
    { code: "EK412", label: "Emirates: DXB -> SYD" },
    { code: "ET500", label: "Ethiopian: ADD -> IAD" },
    { code: "ET501", label: "Ethiopian: IAD -> ADD" },
    { code: "EY1", label: "Etihad: AUH -> JFK" },
    { code: "EY2", label: "Etihad: JFK -> AUH" },
    { code: "EY11", label: "Etihad: AUH -> LHR" },
    { code: "FI611", label: "Icelandair: KEF -> JFK" },
    { code: "FI680", label: "Icelandair: SEA -> KEF" },
    { code: "FJ810", label: "Fiji Airways: NAN -> LAX" },
    { code: "FZ1", label: "Flydubai: DXB -> DOH" },
    { code: "GF2", label: "Gulf Air: LHR -> BAH" },
    { code: "IB3166", label: "Iberia: MAD -> LHR" },
    { code: "IB6250", label: "Iberia: JFK -> MAD" },
    { code: "IB6251", label: "Iberia: MAD -> JFK" },
    { code: "JL1", label: "Japan Airlines: SFO -> HND" },
    { code: "JL2", label: "Japan Airlines: HND -> SFO" },
    { code: "JL3", label: "Japan Airlines: JFK -> HND" },
    { code: "JL4", label: "Japan Airlines: HND -> JFK" },
    { code: "JL5", label: "Japan Airlines: JFK -> HND" },
    { code: "JL6", label: "Japan Airlines: HND -> JFK" },
    { code: "KE1", label: "Korean Air: ICN -> HNL" },
    { code: "KE2", label: "Korean Air: HNL -> ICN" },
    { code: "KE11", label: "Korean Air: ICN -> LAX" },
    { code: "KE17", label: "Korean Air: ICN -> LAX" },
    { code: "KE81", label: "Korean Air: ICN -> JFK" },
    { code: "KE901", label: "Korean Air: ICN -> CDG" },
    { code: "KL601", label: "KLM: AMS -> LAX" },
    { code: "KL602", label: "KLM: LAX -> AMS" },
    { code: "KL641", label: "KLM: AMS -> JFK" },
    { code: "KL642", label: "KLM: JFK -> AMS" },
    { code: "LA500", label: "LATAM: SCL -> MIA" },
    { code: "LA501", label: "LATAM: MIA -> SCL" },
    { code: "LA600", label: "LATAM: SCL -> LAX" },
    { code: "LH400", label: "Lufthansa: FRA -> JFK" },
    { code: "LH401", label: "Lufthansa: JFK -> FRA" },
    { code: "LH410", label: "Lufthansa: MUC -> JFK" },
    { code: "LH422", label: "Lufthansa: FRA -> BOS" },
    { code: "LH430", label: "Lufthansa: FRA -> ORD" },
    { code: "LH454", label: "Lufthansa: FRA -> SFO" },
    { code: "LH490", label: "Lufthansa: FRA -> SEA" },
    { code: "LO1", label: "LOT Polish: WAW -> ORD" },
    { code: "LO3", label: "LOT Polish: WAW -> JFK" },
    { code: "LX14", label: "Swiss: ZRH -> JFK" },
    { code: "LX15", label: "Swiss: JFK -> ZRH" },
    { code: "LX38", label: "Swiss: ZRH -> SFO" },
    { code: "LX40", label: "Swiss: ZRH -> LAX" },
    { code: "LY1", label: "El Al: TLV -> JFK" },
    { code: "LY2", label: "El Al: JFK -> TLV" },
    { code: "LY7", label: "El Al: TLV -> JFK" },
    { code: "LY8", label: "El Al: JFK -> TLV" },
    { code: "MH1", label: "Malaysia Airlines: LHR -> KUL" },
    { code: "MH2", label: "Malaysia Airlines: KUL -> LHR" },
    { code: "MH3", label: "Malaysia Airlines: LHR -> KUL" },
    { code: "MH4", label: "Malaysia Airlines: KUL -> LHR" },
    { code: "MS985", label: "EgyptAir: CAI -> JFK" },
    { code: "MU587", label: "China Eastern: PVG -> JFK" },
    { code: "NH1", label: "All Nippon Airways: IAD -> NRT" },
    { code: "NH2", label: "All Nippon Airways: NRT -> IAD" },
    { code: "NH5", label: "All Nippon Airways: LAX -> NRT" },
    { code: "NH6", label: "All Nippon Airways: NRT -> LAX" },
    { code: "NH7", label: "All Nippon Airways: SFO -> NRT" },
    { code: "NH8", label: "All Nippon Airways: NRT -> SFO" },
    { code: "NH106", label: "All Nippon Airways: HND -> LAX" },
    { code: "NZ1", label: "Air New Zealand: JFK -> AKL" },
    { code: "NZ2", label: "Air New Zealand: AKL -> JFK" },
    { code: "NZ5", label: "Air New Zealand: LAX -> AKL" },
    { code: "NZ6", label: "Air New Zealand: AKL -> LAX" },
    { code: "OS87", label: "Austrian Airlines: VIE -> JFK" },
    { code: "OS88", label: "Austrian Airlines: JFK -> VIE" },
    { code: "OZ201", label: "Asiana: ICN -> LAX" },
    { code: "OZ202", label: "Asiana: LAX -> ICN" },
    { code: "OZ221", label: "Asiana: JFK -> ICN" },
    { code: "QF1", label: "Qantas: SYD -> LHR" },
    { code: "QF2", label: "Qantas: LHR -> SYD" },
    { code: "QF9", label: "Qantas: PER -> LHR" },
    { code: "QF10", label: "Qantas: LHR -> PER" },
    { code: "QF11", label: "Qantas: SYD -> LAX" },
    { code: "QF12", label: "Qantas: LAX -> SYD" },
    { code: "QF93", label: "Qantas: MEL -> LAX" },
    { code: "QR1", label: "Qatar Airways: DOH -> LHR" },
    { code: "QR2", label: "Qatar Airways: LHR -> DOH" },
    { code: "QR3", label: "Qatar Airways: DOH -> LHR" },
    { code: "QR701", label: "Qatar Airways: DOH -> JFK" },
    { code: "QR702", label: "Qatar Airways: JFK -> DOH" },
    { code: "QR908", label: "Qatar Airways: DOH -> SYD" },
    { code: "SA234", label: "South African Airways: JNB -> LHR" },
    { code: "SK903", label: "SAS: ARN -> EWR" },
    { code: "SK904", label: "SAS: EWR -> ARN" },
    { code: "SK909", label: "SAS: CPH -> EWR" },
    { code: "SK935", label: "SAS: CPH -> SFO" },
    { code: "SQ1", label: "Singapore Airlines: SFO -> SIN" },
    { code: "SQ2", label: "Singapore Airlines: SIN -> SFO" },
    { code: "SQ11", label: "Singapore Airlines: LAX -> NRT" },
    { code: "SQ12", label: "Singapore Airlines: NRT -> LAX" },
    { code: "SQ21", label: "Singapore Airlines: EWR -> SIN" },
    { code: "SQ22", label: "Singapore Airlines: SIN -> EWR" },
    { code: "SQ23", label: "Singapore Airlines: JFK -> SIN" },
    { code: "SQ24", label: "Singapore Airlines: SIN -> JFK" },
    { code: "SQ25", label: "Singapore Airlines: JFK -> FRA" },
    { code: "SQ26", label: "Singapore Airlines: FRA -> JFK" },
    { code: "SV20", label: "Saudia: JFK -> JED" },
    { code: "SV21", label: "Saudia: JED -> JFK" },
    { code: "TG910", label: "Thai Airways: BKK -> LHR" },
    { code: "TG911", label: "Thai Airways: LHR -> BKK" },
    { code: "TG930", label: "Thai Airways: BKK -> CDG" },
    { code: "TK1", label: "Turkish Airlines: IST -> JFK" },
    { code: "TK2", label: "Turkish Airlines: JFK -> IST" },
    { code: "TK3", label: "Turkish Airlines: IST -> JFK" },
    { code: "TK4", label: "Turkish Airlines: JFK -> IST" },
    { code: "TK7", label: "Turkish Airlines: IST -> IAD" },
    { code: "TK9", label: "Turkish Airlines: IST -> LAX" },
    { code: "TK10", label: "Turkish Airlines: LAX -> IST" },
    { code: "TP209", label: "TAP Air Portugal: OPO -> JFK" },
    { code: "UA1", label: "United Airlines: SFO -> SIN" },
    { code: "UA2", label: "United Airlines: SIN -> SFO" },
    { code: "UA3", label: "United Airlines: EWR -> IAH" },
    { code: "UA4", label: "United Airlines: IAH -> EWR" },
    { code: "UA5", label: "United Airlines: IAH -> LHR" },
    { code: "UA14", label: "United Airlines: EWR -> LHR" },
    { code: "UA15", label: "United Airlines: LHR -> EWR" },
    { code: "UA20", label: "United Airlines: IAH -> AMS" },
    { code: "UA32", label: "United Airlines: LAX -> NRT" },
    { code: "UA35", label: "United Airlines: SFO -> KIX" },
    { code: "UA57", label: "United Airlines: EWR -> CDG" },
    { code: "UA85", label: "United Airlines: EWR -> TLV" },
    { code: "UA86", label: "United Airlines: TLV -> EWR" },
    { code: "UA869", label: "United Airlines: SFO -> HKG" },
    { code: "UA909", label: "United Airlines: ORD -> AMS" },
    { code: "UA924", label: "United Airlines: LHR -> IAD" },
    { code: "UA934", label: "United Airlines: EWR -> LHR" },
    { code: "UA999", label: "United Airlines: EWR -> BRU" },
    { code: "VN1", label: "Vietnam Airlines: HAN -> SGN" },
    { code: "VN31", label: "Vietnam Airlines: SGN -> FRA" },
    { code: "VS1", label: "Virgin Atlantic: LHR -> JFK/EWR" },
    { code: "VS2", label: "Virgin Atlantic: JFK -> LHR" },
    { code: "VS3", label: "Virgin Atlantic: LHR -> JFK" },
    { code: "VS4", label: "Virgin Atlantic: JFK -> LHR" },
    { code: "VS5", label: "Virgin Atlantic: LHR -> MIA" },
    { code: "VS7", label: "Virgin Atlantic: LHR -> LAX" },
    { code: "VS8", label: "Virgin Atlantic: LAX -> LHR" },
    { code: "VS9", label: "Virgin Atlantic: LHR -> JFK" },
    { code: "VS10", label: "Virgin Atlantic: JFK -> LHR" },
    { code: "VS11", label: "Virgin Atlantic: LHR -> BOS" },
    { code: "VS12", label: "Virgin Atlantic: BOS -> LHR" },
    { code: "VS19", label: "Virgin Atlantic: LHR -> SFO" },
    { code: "VS20", label: "Virgin Atlantic: SFO -> LHR" },
    { code: "WS2", label: "WestJet: YYC -> LGW" },
    { code: "WS3", label: "WestJet: YYZ -> LGW" },
    { code: "WS80", label: "WestJet: YVR -> YHZ" },
];