// Common Airline Codes for Autocomplete
export const AIRLINES = [
    { code: "AA", name: "American Airlines" },
    { code: "DL", name: "Delta Air Lines" },
    { code: "UA", name: "United Airlines" },
    { code: "BA", name: "British Airways" },
    { code: "LH", name: "Lufthansa" },
    { code: "AF", name: "Air France" },
    { code: "EK", name: "Emirates" },
    { code: "QR", name: "Qatar Airways" },
    { code: "SQ", name: "Singapore Airlines" },
    { code: "CX", name: "Cathay Pacific" },
    { code: "QF", name: "Qantas" },
    { code: "JL", name: "Japan Airlines" },
    { code: "NH", name: "All Nippon Airways" },
    { code: "KE", name: "Korean Air" },
    { code: "TK", name: "Turkish Airlines" },
    { code: "VS", name: "Virgin Atlantic" },
    { code: "AC", name: "Air Canada" },
    { code: "KL", name: "KLM Royal Dutch Airlines" },
    { code: "LX", name: "Swiss International Air Lines" },
    { code: "IB", name: "Iberia" },
    { code: "AZ", name: "Alitalia" },
    { code: "WN", name: "Southwest Airlines" },
    { code: "B6", name: "JetBlue Airways" },
    { code: "AS", name: "Alaska Airlines" },
    { code: "NK", name: "Spirit Airlines" },
    { code: "F9", name: "Frontier Airlines" },
    { code: "G4", name: "Allegiant Air" },
    { code: "HA", name: "Hawaiian Airlines" },
];

// Mock list of popular flight numbers for demo purposes
export const MOCK_FLIGHTS = [
    { code: "AA100", label: "American Airlines: JFK -> LHR" },
    { code: "AA1", label: "American Airlines: JFK -> LAX" },
    { code: "BA249", label: "British Airways: LHR -> GIG" },
    { code: "BA117", label: "British Airways: LHR -> JFK" },
    { code: "UA1", label: "United Airlines: SFO -> SIN" },
    { code: "UA85", label: "United Airlines: TLV -> EWR" },
    { code: "DL1", label: "Delta Air Lines: JFK -> LHR" },
    { code: "DL444", label: "Delta Air Lines: JFK -> CDG" },
    { code: "EK201", label: "Emirates: DXB -> JFK" },
    { code: "EK1", label: "Emirates: DXB -> LHR" },
    { code: "SQ22", label: "Singapore Airlines: SIN -> EWR" },
    { code: "SQ1", label: "Singapore Airlines: SFO -> SIN" },
    { code: "LH400", label: "Lufthansa: FRA -> JFK" },
    { code: "AF6", label: "Air France: CDG -> JFK" },
    { code: "QF1", label: "Qantas: SYD -> LHR" },
    { code: "QR701", label: "Qatar Airways: DOH -> JFK" },
    { code: "CX888", label: "Cathay Pacific: HKG -> YVR" },
    { code: "TK1", label: "Turkish Airlines: IST -> JFK" },
    { code: "B61", label: "JetBlue: JFK -> FLL" },
    { code: "WN42", label: "Southwest Airlines: DAL -> LAS" },
];