steps:
  # Build the container image
  - name: 'gcr.io/cloud-builders/docker'
    args: ['build', '-t', 'gcr.io/$PROJECT_ID/flight-tracker', '.']

# Push the image to Container Registry
images:
  - 'gcr.io/$PROJECT_ID/flight-tracker'

# Required option when building with a user-specified service account
options:
  logging: CLOUD_LOGGING_ONLY
