pipeline:
  identifier: Build_abhid1234_Developer_1767752195812
  name: Build Developer
  orgIdentifier: default
  projectIdentifier: default_project
  properties:
    ci:
      codebase:
        build: <+input>
        connectorRef: account.Github
        repoName: abhid1234/Developer
  stages:
    - stage:
        identifier: build1
        name: build
        spec:
          caching:
            enabled: true
          cloneCodebase: true
          execution:
            steps:
              - step:
                  type: Run
                  name: npm config
                  identifier: npmconfig
                  spec:
                    shell: Bash
                    command: |
                      # Set up npm authentication
                      echo "//registry.npmjs.org/:_authToken=${NPM_AUTH_TOKEN}" > ~/.npmrc
                      echo "registry=https://registry.npmjs.org/" >> ~/.npmrc
                      echo "always-auth=true" >> ~/.npmrc

                      # Verify npm configuration
                      npm config list
                    envVariables:
                      NPM_AUTH_TOKEN: <+secrets.getValue("NPM_AUTH_TOKEN")>
                  timeout: 10m
              - step:
                  identifier: installdependencies
                  name: install dependencies
                  spec:
                    command: npm install
                  timeout: ""
                  type: Run
              - step:
                  identifier: lint
                  name: lint
                  spec:
                    command: npm run lint
                  timeout: ""
                  type: Run
              - step:
                  identifier: build
                  name: build
                  spec:
                    command: npm run build
                  timeout: ""
                  type: Run
              - step:
                  identifier: dockerbuild
                  name: docker_build
                  spec:
                    caching: true
                    connectorRef: <+input>
                    repo: hello/world
                    tags:
                      - latest
                  timeout: ""
                  type: BuildAndPushDockerRegistry
            rollbackSteps: []
          platform:
            arch: Amd64
            os: Linux
          runtime:
            spec:
              imageName: node:18.17.0
            type: Cloud
        type: CI
  description: This pipeline was updated by Harness AI on 2026-01-07 02:37:46 UTC by Abhi Das.
  tags:
    ai_generated: "true"
