pipeline:
  name: FlightTracker Pipeline
  identifier: FlightTracker_Pipeline
  projectIdentifier: default_project
  orgIdentifier: default
  tags: {}
  properties:
    ci:
      codebase:
        connectorRef: account.Github
        repoName: abhid1234/FlightTracker
        build:
          type: branch
          spec:
            branch: main
  stages:
    - stage:
        name: Build FlightTracker
        identifier: Build_FlightTracker
        description: ""
        type: CI
        spec:
          cloneCodebase: true
          caching:
            enabled: true
            override: true
          buildIntelligence:
            enabled: true
          platform:
            os: Linux
            arch: Amd64
          runtime:
            type: Cloud
            spec: {}
          execution:
            steps:
              - step:
                  type: BuildAndPushGAR
                  name: BuildAndPushGAR_1
                  identifier: BuildAndPushGAR_1
                  spec:
                    connectorRef: Harness_GCP_BuildDeploy_Pipeline
                    host: gcr.io
                    projectID: elegant-cipher-335206
                    imageName: flight-tracker
                    tags:
                      - gcr.io/elegant-cipher-335206/flight-tracker
